
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: minidb
    
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    - DEBUG=True
    - POSTGRES_HOST=db
    - POSTGRES_NAME=minidb
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_PORT=5432

volumes:
  postgres_data:
  media_volume: